/**
 * One-shot helper: reads local MVP data and writes a single SQL file
 * to /tmp/askine-import.sql containing INSERTs for lessons + chunks.
 *
 * Run-once script — useful when local DATABASE_URL is broken and we
 * have to execute the import via Supabase MCP in batches instead.
 *
 *   npx tsx scripts/cli/_generate-import-sql.ts <courseId>
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve as resolvePath } from "node:path";
import Database from "better-sqlite3";
import * as sqliteVec from "sqlite-vec";

const courseId = process.argv[2];
if (!courseId) {
  console.error("Usage: npx tsx scripts/cli/_generate-import-sql.ts <courseId>");
  process.exit(1);
}

interface LessonJson {
  id: string;
  lessonNumber: number | null;
  title: string;
  durationSec: number;
  embedUrl: string;
  hlsUrl: string;
  thumbnailUrl: string;
}

interface TranscriptJson {
  lessonId: string;
  language: string;
  segments: { start: number; end: number; text: string }[];
}

function quote(s: string | null): string {
  if (s === null) return "NULL";
  return `'${s.replace(/'/g, "''")}'`;
}
function jsonbLit(v: unknown): string {
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}
function vecLit(arr: Float32Array): string {
  return `'[${Array.from(arr).join(",")}]'::vector`;
}

const root = process.cwd();
const lessonsLocal: LessonJson[] = JSON.parse(readFileSync(resolvePath(root, "data/lessons.json"), "utf8"));

const transcriptsDir = resolvePath(root, "data/transcripts");
const transcriptsByLessonId = new Map<string, TranscriptJson>();
for (const f of readdirSync(transcriptsDir)) {
  if (!f.endsWith(".json")) continue;
  const t: TranscriptJson = JSON.parse(readFileSync(resolvePath(transcriptsDir, f), "utf8"));
  transcriptsByLessonId.set(t.lessonId, t);
}

// Stable: we generate DB UUIDs here so chunks can reference them in the same SQL file.
// We use the local Panda video id as source_video_id; the Postgres id is generated by us
// (a UUIDv5-like deterministic mapping isn't needed — random UUIDs are fine).
function uuid(): string {
  // basic random uuid v4
  const b = new Uint8Array(16);
  for (let i = 0; i < 16; i++) b[i] = Math.floor(Math.random() * 256);
  b[6] = (b[6] & 0x0f) | 0x40;
  b[8] = (b[8] & 0x3f) | 0x80;
  const hex = Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const lessonIdMap = new Map<string, string>();
const lessonInserts: string[] = [];
for (const l of lessonsLocal) {
  const newId = uuid();
  lessonIdMap.set(l.id, newId);
  const t = transcriptsByLessonId.get(l.id);
  const transcript = t ? jsonbLit({ language: t.language, segments: t.segments }) : "NULL";
  lessonInserts.push(
    `INSERT INTO lessons (id, course_id, source_video_id, lesson_number, title, duration_sec, hls_url, embed_url, thumbnail_url, transcript, transcript_source) VALUES (` +
      `'${newId}', '${courseId}', '${l.id}', ${l.lessonNumber ?? "NULL"}, ${quote(l.title)}, ${l.durationSec}, ${quote(l.hlsUrl)}, ${quote(l.embedUrl)}, ${quote(l.thumbnailUrl)}, ${transcript}, 'whisper');`,
  );
}

// Chunks from sqlite-vec — need to load the extension before vec0 virtual table is queryable
const sqliteDb = new Database(resolvePath(root, "data/vectors.db"), { readonly: true });
sqliteVec.load(sqliteDb);
const chunkRows = sqliteDb.prepare(`
  SELECT c.lesson_id, c.start_sec, c.end_sec, c.text, v.embedding
  FROM chunks c
  JOIN chunks_vec v ON v.rowid = c.id
  ORDER BY c.id ASC
`).all() as Array<{ lesson_id: string; start_sec: number; end_sec: number; text: string; embedding: Buffer }>;
sqliteDb.close();

const chunkInserts: string[] = [];
for (const c of chunkRows) {
  const dbLessonId = lessonIdMap.get(c.lesson_id);
  if (!dbLessonId) continue;
  const f32 = new Float32Array(c.embedding.buffer, c.embedding.byteOffset, c.embedding.byteLength / 4);
  chunkInserts.push(
    `INSERT INTO chunks (course_id, source_type, lesson_id, start_sec, end_sec, text, embedding) VALUES (` +
      `'${courseId}', 'lesson', '${dbLessonId}', ${c.start_sec}, ${c.end_sec}, ${quote(c.text)}, ${vecLit(f32)});`,
  );
}

const head =
  `-- Generated import: ${lessonInserts.length} lessons, ${chunkInserts.length} chunks\n` +
  `BEGIN;\n` +
  `DELETE FROM chunks WHERE course_id = '${courseId}';\n` +
  `DELETE FROM lessons WHERE course_id = '${courseId}';\n`;
const tail = `\nUPDATE courses SET ingest_status = 'ready', updated_at = NOW() WHERE id = '${courseId}';\nCOMMIT;\n`;

const sql = head + lessonInserts.join("\n") + "\n" + chunkInserts.join("\n") + tail;
writeFileSync("/tmp/askine-import.sql", sql);

console.log(`Wrote /tmp/askine-import.sql`);
console.log(`  lessons: ${lessonInserts.length}`);
console.log(`  chunks:  ${chunkInserts.length}`);
console.log(`  size:    ${(sql.length / 1024).toFixed(1)} KB`);
